version: "3.4"

services:
  backend:
    build:
      context: .
      target: development
    container_name: bolid-back
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: bolid-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: